env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/essential
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {}
