version: '3'

services:
  nginx:
    build:
      context: images/nginx
      dockerfile: Dockerfile
      args:
        - HOME=${HOME}
        - HUB=${HUB}
        - JOBS=${JOBS}
        - UID=${UID}
        - USER=${USER}
        - ENV=${APP_ENV}
        - FRONT_WORKDIR=${FRONT_WORKDIR}
        - NUXT_PORT=${NUXT_PORT}
        - NGINX_WORKDIR=${NGINX_WORKDIR}
    container_name: ${NGINX_WORKDIR}
    restart: always
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    working_dir: /var/www/${NGINX_WORKDIR}
    volumes:
      - .:/var/www/${NGINX_WORKDIR}
    depends_on:
      - front

  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONT_WORKDIR=${FRONT_WORKDIR}
        - NUXT_PORT=${NUXT_PORT}
    container_name: ${FRONT_WORKDIR}
    restart: always


