version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONT_WORKDIR=${FRONT_WORKDIR}
        - NUXT_PORT=${NUXT_PORT}
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "3"


